### ISSUE TITLE
Does DBMD require TensorRT?

### ISSUE THREAD

**Issue by patwin2** [MiaoLab20/DBMD#3]
Hi. I've run into a problem trying to run the test simulation. It seems that the CMD portion runs to completion. Equil-prep runs and generates equil-prep-0 out files (log, dcd, mdout, rst). However, it then fails with the following messages:

--------------------------------------------------------------------------------

2023-06-27 02:52:51.221965: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-06-27 02:52:51.790702: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:51.797260: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:51.798001: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:52.741075: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:52.741630: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:52.742138: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-27 02:52:52.742632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9184 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:09:00.0, compute capability: 7.5
Traceback (most recent call last):
  File "/home/pwintrod/DBMD/simulationEquilStage.py", line 53, in <module>
    if cycle == 0: df = pd.read_csv("equil-prep.mdout", names=column_names, header=0, delimiter="\t")
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'equil-prep.mdout'
Traceback (most recent call last):
  File "/home/pwintrod/DBMD/simulationProdStage.py", line 23, in <module>
    if cycle == 0: simulation.loadState("equil.rst")
  File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/openmm/app/simulation.py", line 340, in loadState
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'equil.rst'

----------------------------------------------------------------------------------

Is this just a matter of installing TensorRT, or is there something else I'm missing?

Thanks for your help.

**Comment by hungd238** [comment]
Hi. I don't think it is an issue with TensorRT since it seems to me that your pre-equilibration stage was not run properly due to the presence of this line:

File "/home/pwintrod/anaconda3/envs/deepmd/lib/python3.9/site-packages/pandas/io/common.py", line 859, in get_handle
handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'equil-prep.mdout'

The cMD and pre-equilibration part do not have any deep learning (and in turn, TensorRT) involved in them. Can you perhaps check your equil-prep-0.mdout file and check if there is anything in it? I am not very familiar with the NUMA mode, so that could possibly be the issue?

This is a normal commandline output that you should see from a DBMD run. Perhaps it may help you resolve your issue:

2023-06-28 21:39:07.111965: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 21:39:07.659811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14780 MB memory:  -> device: 0, name: Quadro RTX 5000, pci bus id: 0000:17:00.0, compute capability: 7.5
Executing: cp '--' 'gamd-restart.dat' 'cmd-restart.dat'
2023-06-28 21:43:45.527469: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 21:43:46.107499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14780 MB memory:  -> device: 0, name: Quadro RTX 5000, pci bus id: 0000:17:00.0, compute capability: 7.5
2023-06-28 21:43:57.093624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14780 MB memory:  -> device: 0, name: Quadro RTX 5000, pci bus id: 0000:17:00.0, compute capability: 7.5

Please let me know after you have checked your equil-prep-0.mdout file.

**Comment by patwin2** [comment]
There's nothing obviously strange in the equil-prep-0.mdout file. It outputs 25,000 lines and neither the potential nor the total energy have exploded to crazy values. Here are the last few lines:

---------------------------------------------------------------------------------
12499400	-10835.857421875	-9255.460205078125	326.59466523561827	0.7967212476780444	38.9	11:39:48	-12120.595703125	0.0	1284.7393798828125	0.0	0.0	0.0

12499500	-10866.9375	-9375.07470703125	308.29871393637524	0.7967212476780444	38.9	11:39:47	-12118.9658203125	0.0	1252.0294189453125	0.0	0.0	0.0

12499600	-11038.5625	-9419.3017578125	334.6259499847476	0.7967212476780444	38.9	11:39:46	-12249.962890625	0.0	1211.3984375	0.0	0.0	0.0

12499700	-11045.0927734375	-9401.422607421875	339.6702436085356	0.7967212476780444	38.9	11:39:46	-12256.52734375	0.0	1211.43505859375	0.0	0.0	0.0

12499800	-10973.259765625	-9506.7431640625	303.06083398484026	0.7967212476780444	38.9	11:39:45	-12224.3828125	0.0	1251.1220703125	0.0	0.0	0.0

12499900	-10883.953125	-9383.902099609375	309.9908410790147	0.7967212476780444	38.9	11:39:44	-12151.78515625	0.0	1267.83203125	0.0	0.0	0.0

12500000	-10986.05078125	-9561.405517578125	294.40797416199626	0.7967212476780444	38.9	11:39:43	-12249.8994140625	0.0	1263.8499755859375	0.0	0.0	0.0
------------------------------------------------------------------------------------

Thanks.

**Comment by hungd238** [comment]
Can you perhaps check if the **gamd-restart.dat** and especially **equil-prep.mdout** file exist after your pre-equilibration simulation? These files are essential for performing the deep learning and continuing your simulations. The **equil-prep.mdout** file was generated by the following command at the end of the **simulationEquilPrepStage.py**:

    os.system("scp equil-prep-"+str(cycle)+".mdout equil-prep.mdout")
    os.system("scp gamd-restart.dat equil-prep-"+str(cycle)+".restart.dat")
    os.system("scp equil-prep-"+str(cycle)+".rst equil-prep.rst")

Python sometimes requires permission to properly perform those **os.system** commands, and I feel like this could be the problem given the presence of this line in your output:

_FileNotFoundError: [Errno 2] No such file or directory: 'equil-prep.mdout'_

Can you double check the presence and content of these files and let me know if they are properly generated?

**Comment by patwin2** [comment]
gamd-restart.dat was generated. Here are the contents:

--------------------------------------------------------------------
#Parameters	Values(kcal/mol)
(0)Steps:	2500000
(1)Boosted VminD:	225.1414778583592
(2)Boosted VmaxD:	331.5285560505796
(3)DihedralRefEnergy:	331.5285560505796
(4)Final DihedralBoost:	3.4848168589377035
(5)Final k0D:	1.0
(6)Boosted VminP:	-2674.3808257648184
(7)Boosted VmaxP:	-2491.752966939882
(8)TotalRefEnergy:	-2491.752966939882
(9)Final TotalBoost:	1.8002007069346293
(10)Final k0P:	0.05
-----------------------------------------------------------------------

However, equil-prep.mdout was not generated.

**Comment by hungd238** [comment]
As I suspected. Can you confirm what your OS system is? If it is **Linux** or **MacOS**, I believe you can use these python commands just fine:

```
os.system("scp equil-prep-"+str(cycle)+".mdout equil-prep.mdout")
os.system("scp gamd-restart.dat equil-prep-"+str(cycle)+".restart.dat")
os.system("scp equil-prep-"+str(cycle)+".rst equil-prep.rst")
```

If your OS system is **Windows**, you may need to give python proper permission to run commands with _os.system_ or modify the commands inside _os.system(" ")_ since **Windows** uses a different set of terminal commands.
